devtools::load_all ()
message ("getting kathmandu schools ... ", appendLF = FALSE)
get_who_data (city = "kathmandu", key = "building", value = "school")
message ("\ndone; getting accra schools ... ", appendLF = FALSE)
get_who_data (city = "accra", key = "building", value = "school")
message ("\ndone")
